RGB_MATRIX_EFFECT(PUDDLE)
#ifdef RGB_MATRIX_CUSTOM_EFFECT_IMPLS

#ifdef RGB_MATRIX_KEYREACTIVE_ENABLED

bool effect_runner_puddle(uint8_t start, effect_params_t* params, reactive_splash_f effect_func) {
    RGB_MATRIX_USE_LIMITS(led_min, led_max);

    uint8_t count = g_last_hit_tracker.count;
    for (uint8_t i = led_min; i < led_max; i++) {
        RGB_MATRIX_TEST_LED_FLAGS();
        HSV hsv = rgb_matrix_config.hsv;
        for (uint8_t j = start; j < count; j++) {
            int16_t  dx   = g_led_config.point[i].x - g_last_hit_tracker.x[j];
            int16_t  dy   = g_led_config.point[i].y - g_last_hit_tracker.y[j];
            uint8_t  dist = sqrt16(dx * dx + dy * dy);
            uint16_t tick = scale16by8(g_last_hit_tracker.tick[j], qadd8(rgb_matrix_config.speed, 1));
            hsv           = effect_func(hsv, dx, dy, dist, tick);
        }
        // hsv.v   = scale8(hsv.v, rgb_matrix_config.hsv.v);
        RGB rgb = rgb_matrix_hsv_to_rgb(hsv);
        rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
    }
    return rgb_matrix_check_finished_leds(led_max);
}

static HSV PUDDLE_math(HSV hsv, int16_t dx, int16_t dy, uint8_t dist, uint16_t tick) {
    uint16_t effect = tick - dist;
    if (effect > 255) effect = 255;
    if (dist > 36) effect =  255;
    hsv.v = qsub8(hsv.v, 255 - effect);
    return hsv;
}

bool PUDDLE(effect_params_t* params) { return effect_runner_puddle(0, params, &PUDDLE_math); }

#endif  // ENABLE_RGB_MATRIX_SOLID_REACTIVE
#endif // RGB_MATRIX_CUSTOM_EFFECT_IMPLS
